// Generated by gencpp from file nasa_r2_common_msgs/JointControlCalibrationMode.msg
// DO NOT EDIT!


#ifndef NASA_R2_COMMON_MSGS_MESSAGE_JOINTCONTROLCALIBRATIONMODE_H
#define NASA_R2_COMMON_MSGS_MESSAGE_JOINTCONTROLCALIBRATIONMODE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nasa_r2_common_msgs
{
template <class ContainerAllocator>
struct JointControlCalibrationMode_
{
  typedef JointControlCalibrationMode_<ContainerAllocator> Type;

  JointControlCalibrationMode_()
    : state(0)  {
    }
  JointControlCalibrationMode_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(IGNORE)
  #undef IGNORE
#endif
#if defined(_WIN32) && defined(DISABLE)
  #undef DISABLE
#endif
#if defined(_WIN32) && defined(ENABLE)
  #undef ENABLE
#endif
#if defined(_WIN32) && defined(UNCALIBRATED)
  #undef UNCALIBRATED
#endif

  enum {
    IGNORE = 0u,
    DISABLE = 1u,
    ENABLE = 2u,
    UNCALIBRATED = 3u,
  };


  typedef boost::shared_ptr< ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator> const> ConstPtr;

}; // struct JointControlCalibrationMode_

typedef ::nasa_r2_common_msgs::JointControlCalibrationMode_<std::allocator<void> > JointControlCalibrationMode;

typedef boost::shared_ptr< ::nasa_r2_common_msgs::JointControlCalibrationMode > JointControlCalibrationModePtr;
typedef boost::shared_ptr< ::nasa_r2_common_msgs::JointControlCalibrationMode const> JointControlCalibrationModeConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator1> & lhs, const ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator1> & lhs, const ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nasa_r2_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37d6fda8e16d375dbb150fda1a045756";
  }

  static const char* value(const ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37d6fda8e16d375dULL;
  static const uint64_t static_value2 = 0xbb150fda1a045756ULL;
};

template<class ContainerAllocator>
struct DataType< ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nasa_r2_common_msgs/JointControlCalibrationMode";
  }

  static const char* value(const ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 state\n"
"uint8 IGNORE       = 0\n"
"uint8 DISABLE      = 1\n"
"uint8 ENABLE       = 2\n"
"uint8 UNCALIBRATED = 3\n"
;
  }

  static const char* value(const ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointControlCalibrationMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nasa_r2_common_msgs::JointControlCalibrationMode_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NASA_R2_COMMON_MSGS_MESSAGE_JOINTCONTROLCALIBRATIONMODE_H
