// Generated by gencpp from file nasa_r2_common_msgs/LabeledTrajectoryMonitorFactors.msg
// DO NOT EDIT!


#ifndef NASA_R2_COMMON_MSGS_MESSAGE_LABELEDTRAJECTORYMONITORFACTORS_H
#define NASA_R2_COMMON_MSGS_MESSAGE_LABELEDTRAJECTORYMONITORFACTORS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nasa_r2_common_msgs
{
template <class ContainerAllocator>
struct LabeledTrajectoryMonitorFactors_
{
  typedef LabeledTrajectoryMonitorFactors_<ContainerAllocator> Type;

  LabeledTrajectoryMonitorFactors_()
    : originator()
    , joint_names()
    , torqueLimitFactors()
    , distanceFactors()  {
    }
  LabeledTrajectoryMonitorFactors_(const ContainerAllocator& _alloc)
    : originator(_alloc)
    , joint_names(_alloc)
    , torqueLimitFactors(_alloc)
    , distanceFactors(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _originator_type;
  _originator_type originator;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _joint_names_type;
  _joint_names_type joint_names;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _torqueLimitFactors_type;
  _torqueLimitFactors_type torqueLimitFactors;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _distanceFactors_type;
  _distanceFactors_type distanceFactors;





  typedef boost::shared_ptr< ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator> const> ConstPtr;

}; // struct LabeledTrajectoryMonitorFactors_

typedef ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<std::allocator<void> > LabeledTrajectoryMonitorFactors;

typedef boost::shared_ptr< ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors > LabeledTrajectoryMonitorFactorsPtr;
typedef boost::shared_ptr< ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors const> LabeledTrajectoryMonitorFactorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator1> & lhs, const ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator2> & rhs)
{
  return lhs.originator == rhs.originator &&
    lhs.joint_names == rhs.joint_names &&
    lhs.torqueLimitFactors == rhs.torqueLimitFactors &&
    lhs.distanceFactors == rhs.distanceFactors;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator1> & lhs, const ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nasa_r2_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a48b940794366a56997943ecd6977867";
  }

  static const char* value(const ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa48b940794366a56ULL;
  static const uint64_t static_value2 = 0x997943ecd6977867ULL;
};

template<class ContainerAllocator>
struct DataType< ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nasa_r2_common_msgs/LabeledTrajectoryMonitorFactors";
  }

  static const char* value(const ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string originator\n"
"string[] joint_names\n"
"float64[] torqueLimitFactors\n"
"float64[] distanceFactors\n"
;
  }

  static const char* value(const ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.originator);
      stream.next(m.joint_names);
      stream.next(m.torqueLimitFactors);
      stream.next(m.distanceFactors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LabeledTrajectoryMonitorFactors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nasa_r2_common_msgs::LabeledTrajectoryMonitorFactors_<ContainerAllocator>& v)
  {
    s << indent << "originator: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.originator);
    s << indent << "joint_names[]" << std::endl;
    for (size_t i = 0; i < v.joint_names.size(); ++i)
    {
      s << indent << "  joint_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.joint_names[i]);
    }
    s << indent << "torqueLimitFactors[]" << std::endl;
    for (size_t i = 0; i < v.torqueLimitFactors.size(); ++i)
    {
      s << indent << "  torqueLimitFactors[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.torqueLimitFactors[i]);
    }
    s << indent << "distanceFactors[]" << std::endl;
    for (size_t i = 0; i < v.distanceFactors.size(); ++i)
    {
      s << indent << "  distanceFactors[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.distanceFactors[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NASA_R2_COMMON_MSGS_MESSAGE_LABELEDTRAJECTORYMONITORFACTORS_H
