// Generated by gencpp from file nasa_r2_common_msgs/ServoRequest.msg
// DO NOT EDIT!


#ifndef NASA_R2_COMMON_MSGS_MESSAGE_SERVOREQUEST_H
#define NASA_R2_COMMON_MSGS_MESSAGE_SERVOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nasa_r2_common_msgs
{
template <class ContainerAllocator>
struct ServoRequest_
{
  typedef ServoRequest_<ContainerAllocator> Type;

  ServoRequest_()
    : joint()
    , state(false)  {
    }
  ServoRequest_(const ContainerAllocator& _alloc)
    : joint(_alloc)
    , state(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _joint_type;
  _joint_type joint;

   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ServoRequest_

typedef ::nasa_r2_common_msgs::ServoRequest_<std::allocator<void> > ServoRequest;

typedef boost::shared_ptr< ::nasa_r2_common_msgs::ServoRequest > ServoRequestPtr;
typedef boost::shared_ptr< ::nasa_r2_common_msgs::ServoRequest const> ServoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator1> & lhs, const ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint == rhs.joint &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator1> & lhs, const ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nasa_r2_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84ae688f7219fea2850abe26519fc2d0";
  }

  static const char* value(const ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84ae688f7219fea2ULL;
  static const uint64_t static_value2 = 0x850abe26519fc2d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nasa_r2_common_msgs/ServoRequest";
  }

  static const char* value(const ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string joint\n"
"bool state\n"
;
  }

  static const char* value(const ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nasa_r2_common_msgs::ServoRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.joint);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NASA_R2_COMMON_MSGS_MESSAGE_SERVOREQUEST_H
