// Generated by gencpp from file nasa_r2_common_msgs/SetJointModeRequest.msg
// DO NOT EDIT!


#ifndef NASA_R2_COMMON_MSGS_MESSAGE_SETJOINTMODEREQUEST_H
#define NASA_R2_COMMON_MSGS_MESSAGE_SETJOINTMODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nasa_r2_common_msgs
{
template <class ContainerAllocator>
struct SetJointModeRequest_
{
  typedef SetJointModeRequest_<ContainerAllocator> Type;

  SetJointModeRequest_()
    : arm_name()  {
    }
  SetJointModeRequest_(const ContainerAllocator& _alloc)
    : arm_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _arm_name_type;
  _arm_name_type arm_name;





  typedef boost::shared_ptr< ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetJointModeRequest_

typedef ::nasa_r2_common_msgs::SetJointModeRequest_<std::allocator<void> > SetJointModeRequest;

typedef boost::shared_ptr< ::nasa_r2_common_msgs::SetJointModeRequest > SetJointModeRequestPtr;
typedef boost::shared_ptr< ::nasa_r2_common_msgs::SetJointModeRequest const> SetJointModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator1> & lhs, const ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.arm_name == rhs.arm_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator1> & lhs, const ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nasa_r2_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ddc5460af992861cb686e55ffa09231";
  }

  static const char* value(const ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ddc5460af992861ULL;
  static const uint64_t static_value2 = 0xcb686e55ffa09231ULL;
};

template<class ContainerAllocator>
struct DataType< ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nasa_r2_common_msgs/SetJointModeRequest";
  }

  static const char* value(const ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string arm_name\n"
;
  }

  static const char* value(const ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arm_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJointModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nasa_r2_common_msgs::SetJointModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "arm_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.arm_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NASA_R2_COMMON_MSGS_MESSAGE_SETJOINTMODEREQUEST_H
