// Generated by gencpp from file nasa_r2_common_msgs/SystemCore.msg
// DO NOT EDIT!


#ifndef NASA_R2_COMMON_MSGS_MESSAGE_SYSTEMCORE_H
#define NASA_R2_COMMON_MSGS_MESSAGE_SYSTEMCORE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nasa_r2_common_msgs
{
template <class ContainerAllocator>
struct SystemCore_
{
  typedef SystemCore_<ContainerAllocator> Type;

  SystemCore_()
    : id()
    , speed(0.0)
    , load(0.0)
    , failure(false)  {
    }
  SystemCore_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , speed(0.0)
    , load(0.0)
    , failure(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _id_type;
  _id_type id;

   typedef double _speed_type;
  _speed_type speed;

   typedef double _load_type;
  _load_type load;

   typedef uint8_t _failure_type;
  _failure_type failure;





  typedef boost::shared_ptr< ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator> const> ConstPtr;

}; // struct SystemCore_

typedef ::nasa_r2_common_msgs::SystemCore_<std::allocator<void> > SystemCore;

typedef boost::shared_ptr< ::nasa_r2_common_msgs::SystemCore > SystemCorePtr;
typedef boost::shared_ptr< ::nasa_r2_common_msgs::SystemCore const> SystemCoreConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator1> & lhs, const ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.speed == rhs.speed &&
    lhs.load == rhs.load &&
    lhs.failure == rhs.failure;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator1> & lhs, const ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nasa_r2_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f24d56ccce4448beee59c654a367c906";
  }

  static const char* value(const ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf24d56ccce4448beULL;
  static const uint64_t static_value2 = 0xee59c654a367c906ULL;
};

template<class ContainerAllocator>
struct DataType< ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nasa_r2_common_msgs/SystemCore";
  }

  static const char* value(const ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string       id\n"
"float64      speed\n"
"float64     load\n"
"bool        failure\n"
;
  }

  static const char* value(const ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.speed);
      stream.next(m.load);
      stream.next(m.failure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemCore_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nasa_r2_common_msgs::SystemCore_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.id);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "load: ";
    Printer<double>::stream(s, indent + "  ", v.load);
    s << indent << "failure: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.failure);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NASA_R2_COMMON_MSGS_MESSAGE_SYSTEMCORE_H
