// Generated by gencpp from file gazebo_taskboard/ManipulatePowerSwitchRequest.msg
// DO NOT EDIT!


#ifndef GAZEBO_TASKBOARD_MESSAGE_MANIPULATEPOWERSWITCHREQUEST_H
#define GAZEBO_TASKBOARD_MESSAGE_MANIPULATEPOWERSWITCHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_taskboard
{
template <class ContainerAllocator>
struct ManipulatePowerSwitchRequest_
{
  typedef ManipulatePowerSwitchRequest_<ContainerAllocator> Type;

  ManipulatePowerSwitchRequest_()
    : angle(0.0)
    , duration(0.0)  {
    }
  ManipulatePowerSwitchRequest_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;

   typedef double _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ManipulatePowerSwitchRequest_

typedef ::gazebo_taskboard::ManipulatePowerSwitchRequest_<std::allocator<void> > ManipulatePowerSwitchRequest;

typedef boost::shared_ptr< ::gazebo_taskboard::ManipulatePowerSwitchRequest > ManipulatePowerSwitchRequestPtr;
typedef boost::shared_ptr< ::gazebo_taskboard::ManipulatePowerSwitchRequest const> ManipulatePowerSwitchRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator1> & lhs, const ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator1> & lhs, const ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_taskboard

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bec7600c9fce5aa19d66565f6ce396c6";
  }

  static const char* value(const ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbec7600c9fce5aa1ULL;
  static const uint64_t static_value2 = 0x9d66565f6ce396c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_taskboard/ManipulatePowerSwitchRequest";
  }

  static const char* value(const ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle\n"
"float64 duration\n"
;
  }

  static const char* value(const ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManipulatePowerSwitchRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_taskboard::ManipulatePowerSwitchRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_TASKBOARD_MESSAGE_MANIPULATEPOWERSWITCHREQUEST_H
